### ISSUE TITLE
Can you add holoios

### ISSUE THREAD

**Issue by lsp199308** [ryanrudolfoba/SteamDeck-Clover-dualboot#11]
https://github.com/HoloISO/holoiso

Thank you very much

**Comment by ryanrudolfoba** [comment]
i tried to install holoiso but i cant figure it out it wont boot stuck on grub recovery screen. i'll try again sometime

**Comment by ryanrudolfoba** [comment]
I tried again but still cant figure out HoloISO.

Closing this issue - cant add HoloISO as I can't figure out HoloISO it doesnt work for me.
