### ISSUE TITLE
Adding Pop!_OS

### ISSUE THREAD

**Issue by Kabocha-san** [ryanrudolfoba/SteamDeck-Clover-dualboot#12]
Could you if possible please add Pop!_OS?
https://pop.system76.com/
Though it uses systemd-boot and not grub by default

**Comment by ryanrudolfoba** [comment]
yup its possible. I'll add it

**Comment by ryanrudolfoba** [comment]
sorry for the delay on this one.

Pop!OS via clover. Please check video here -

https://youtu.be/cWlz8YFf7Kw

This will be added on the next clover update.
