### ISSUE TITLE
Support GUI app

### ISSUE THREAD

**Issue by dtantono** [ryanrudolfoba/SteamDeck-Clover-dualboot#13]
I know CLI is fine. But, I think not everyone is tech-savvy and comfortable with command line. what do you think?

**Comment by SpazShark** [comment]
Very cool! A few ideas:
1) Can you add an option to add a custom timeout that the user inputs?
2) What happens if they users is running Batocera, etc. as a 3rd OS and wants to default on that?

Great work!

**Comment by ryanrudolfoba** [comment]
Batocera - this is doable, i'll add this.

Custom Timeout - not sure about this. This might break Clover if incorrect values are entered by end user.

**Comment by dtantono** [comment]
Is it possible to change the icon for Windows and Steam OS on OS selection and change wallpaper background as well?

**Comment by ryanrudolfoba** [comment]
> 

Thats done via the themes.

**Comment by dtantono** [comment]
okay, how to do that via GUI application?
![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/29157187/e486170e-98b0-4754-a252-a3ee5cb0796c)

**Comment by ryanrudolfoba** [comment]
Use Dolphin File manager to add / remove themes.

https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot#how-to-add--remove-themes

**Comment by dtantono** [comment]
I see. For change wallpaper So, we just download the theme folder (https://github.com/CloverHackyColor/CloverThemes/tree/master/Greenify) and delete this background jpg file and replace it with our custom image png file and rename it with background on the same location?
https://github.com/CloverHackyColor/CloverThemes/blob/master/Greenify/background.png

BTW, Is it possible to add last booted entry on the GUI app like GRUB? (like if we restart the Steam Deck the boot manager will remember which OS we booted into instead pick each OS manually) because Windows update usually needs to be restarted and it will be helpful to prevent breakage on windows update and accident when booting on different OSes

**Comment by ryanrudolfoba** [comment]
Updated the script and it now contains a GUI / simple menu.

![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/949e0209-abd9-4333-aac6-c9299df6b7ed)

**Comment by dtantono** [comment]
okay so how to remember which OS we booted last time?

**Comment by ryanrudolfoba** [comment]
oh sorry i forgot to add that in. Let me make some quick edits

**Comment by ryanrudolfoba** [comment]
updated!

![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/fa9d4ed4-7e40-40a1-b1ab-ca937de27cf6)
