### ISSUE TITLE
Support traditional PC/laptops for dual-boot settings between windows and Linux

### ISSUE THREAD

**Issue by dnet890** [ryanrudolfoba/SteamDeck-Clover-dualboot#14]
Hi
it will be wonderful if we can use this script for dual boot setup between windows and Linux on traditional PC. what do you think?

**Comment by ryanrudolfoba** [comment]
Yes agreed. Someone tried it on Windows and HoloISO it didnt work, so im trying to make it work on regular linux distro. I think i know how just need time to write it down. Next update will have it

**Comment by ryanrudolfoba** [comment]
the new script does not depend on the "deck" username anymore.

still a long way to go .....

**Comment by DarioCr00** [comment]
Does it work with ubuntu?

**Comment by ryanrudolfoba** [comment]
[Script has been updated to work with Bazzite and SteamOS, using Steam Deck hardware.](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/issues/26)

This is as far as I will go, will be difficult to make it "universal" as there are a lot of configurations and will be difficult to troubleshoot.
