### ISSUE TITLE
uninstall-Clover.sh Missing

### ISSUE THREAD

**Issue by ccsnet** [ryanrudolfoba/SteamDeck-Clover-dualboot#15]
uninstall-Clover.sh is currently missing meaning uninstall is not possible.

Thanks

T

**Comment by ryanrudolfoba** [comment]
You do that via the GUI now

![240741813-8308d81f-99f6-4751-abf1-3ebb8436322a (1)](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/50bc9443-04f5-414d-ac55-4f2a3d178895)

**Comment by ccsnet** [comment]
Thanks. You may want to update the faq on the main page then.

**Comment by ryanrudolfoba** [comment]
ah good catch on the FAQ I'll update it

**Comment by ryanrudolfoba** [comment]
README FAQ section has been updated to use the Clover Toolbox
