### ISSUE TITLE
Error After Reinstall Attempt

### ISSUE THREAD

**Issue by ccsnet** [ryanrudolfoba/SteamDeck-Clover-dualboot#16]
After u installing (due to Windows needing more efi space to be fixed) reinstall ends with this error after entering in the password.

Thanks

T

![20230602_234543](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/2273368/7f685f18-9cb9-4633-b45c-b8b0cbcb1b44)

**Comment by ryanrudolfoba** [comment]
based on that its not able to find config.plist

Can you please try this to show the contents of the directories -

ls ~/SteamDeck-Clover-dualboot/

ls ~/SteamDeck-Clover-dualboot/custom

**Comment by ccsnet** [comment]
Hi Ryan.

Thanks for getting back to me.

Here are the directory listing's you asked to see.

![20230603_202352](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/2273368/43d57e29-d4ca-4578-aba3-c7c5501d95a9)

Thanks

T

**Comment by ryanrudolfoba** [comment]
another clue on the previous screenshot it errors out on the zenity command - locale not supported. Could be a SteamOS quirk as thats the first time i saw an error like that.

I'll keep this in mind and if it happens again for other users i'll ask them to update SteamOS. If it becomes a trend i'll add it to the FAQ.

**Comment by ccsnet** [comment]
Thank you Ryan.

T
