### ISSUE TITLE
Boot menu pops up Windows External SSD when i don't have it installed

### ISSUE THREAD

**Issue by zhengzhongren** [ryanrudolfoba/SteamDeck-Clover-dualboot#17]
Hi,
My boot menu pops up a new boot entry "windows external SSD" when i don't have it installed. I have only install SteamOS, Windows on internal SSD and Batocera. Can you please assist? Thank you so much..

Regards,
Zheng

**Comment by ryanrudolfoba** [comment]
Manually reboot to SteamOS and it will fix it automatically.

I'll push an updated config sometime this week

**Comment by ryanrudolfoba** [comment]
Sorry for late reply. Config and main script has been updated.
