### ISSUE TITLE
Do I need to first install windows 

### ISSUE THREAD

**Issue by GoofyPanncake** [ryanrudolfoba/SteamDeck-Clover-dualboot#18]
I downloaded clover boot loader on my steam deck and when I go to load windows it’s not there so I’m just wondering if I need to install windows and if I do where do I install

**Comment by ryanrudolfoba** [comment]
Sorry for late reply. Ideally have both SteamOS and Windows installed first. Boot to Windows then do the prerequisites for Windows.

Then boot to SteamOS then install the clover script.
