### ISSUE TITLE
While Clover service works it breaks SD Card ext4 in SteamOS

### ISSUE THREAD

**Issue by CarlBraun** [ryanrudolfoba/SteamDeck-Clover-dualboot#19]
SD Card is inside in ext4 format while using windows 11, then i boot a steamos and sd card not mounting, but visible. It somehow fixes with disabling a clover service and choosing boot menu by myself with "-" + "power button". Then reinstalled my sd card.

Clover Boot Manager - Fri Jul 7 02:35:02 AM EEST 2023
BIOS Version : F7A0113
no dump files. no action needed.
Clover EFI entry exists! No need to re-add Clover.
SteamOS EFI entry exists! No need to re-add SteamOS.
*** Current state of EFI entries ****
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0000,0002
Boot0000* Clover - GUI Boot Manager	
HD(1,GPT,d67ba5c5-565d-b042-bdf0-dd7e18115214,0x800,0x20000)/File(EFIclovercloverx64.efi)
Boot0001* Windows Boot Manager	
HD(1,GPT,d67ba5c5-565d-b042-bdf0-dd7e18115214,0x800,0x20000)/File(EFIMicrosoftBootootmgfw.efi)RC
Boot0002* SteamOS	HD(1,GPT,d67ba5c5-565d-b042-bdf0-dd7e18115214,0x800,0x20000)/File(EFIsteamossteamcl.efi)
Boot0003* Windows Boot Manager	
HD(1,GPT,d67ba5c5-565d-b042-bdf0-dd7e18115214,0x800,0x20000)/File(EFIMicrosoftBootootmgfw.efi)57494e444f57530001000
00088000000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d003
4006500370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d0000003100010000001000000004000
0007fff0400

**Comment by CarlBraun** [comment]
> I can't replicate this issue. I'm using WIN10 and from WIN10 i reboot to SteamOS the sdcard works OK i can mount it.

That's because of Windows tries to fix my sd card and shows it like another one, with same name as another somehow.

**Comment by ryanrudolfoba** [comment]
> > I can't replicate this issue. I'm using WIN10 and from WIN10 i reboot to SteamOS the sdcard works OK i can mount it.
> 
> That's because of Windows tries to "defragmentate" "optimize" my sd card and because it looks for windows 11 like my other sd card, with fat32 , with same name somehow.

That sounds totally unrelated to what the service does. This is what the service does -

* Create text file called status.txt
* Capture the date / time and save in status.txt
* Capture the BIOS version and save in status.txt
* Check for EFI dump files and perform cleanup as needed
* Check the state of EFI entries and recreate them as needed
* Rearrange the boot order so that Clover is top priority

**Comment by CarlBraun** [comment]
> > > I can't replicate this issue. I'm using WIN10 and from WIN10 i reboot to SteamOS the sdcard works OK i can mount it.
> > 
> > 
> > That's because of Windows tries to "defragmentate" "optimize" my sd card and because it looks for windows 11 like my other sd card, with fat32 , with same name somehow.
> 
> That sounds totally unrelated to what the service does. This is what the service does -
> 
> * Create text file called status.txt
> * Capture the date / time and save in status.txt
> * Capture the BIOS version and save in status.txt
> * Check for EFI dump files and perform cleanup as needed
> * Check the state of EFI entries and recreate them as needed
> * Rearrange the boot order so that Clover is top priority

ok, than i want you to make a possibility of default boot in clover menu(startup)

**Comment by ryanrudolfoba** [comment]
Main script and config has been updated.
