### ISSUE TITLE
(External SSD) : Status.txt Empty

### ISSUE THREAD

**Issue by andre1892** [ryanrudolfoba/SteamDeck-Clover-dualboot#21]
Hello,
ive did all Steps of your Guide. Windows ist installed on an external SSD and it wont showed up on the Clover GUI. So Ive used step Bye step the "Windows hijacked" Guide and after ive run the Clover Task in Windows and take a look in the Status.txt to See, If the "Clover Gui ans bootsequence" have the same Input ive seen that Clover GUI ist completeply blank and bootsequence isnt shown there. And it wont work: Again no Windows OS showed on the Clover GUI

**Comment by ryanrudolfoba** [comment]
Make sure when doing Windows To Go on external ssd / sdcard it should be formatted as GPT.

**Comment by ryanrudolfoba** [comment]
This is also documented in the FAQ -

![Uploading Screenshot_20230804-021131_Settings.png…]()

**Comment by ryanrudolfoba** [comment]
This is also documented in the FAQ Q0 -

![Screenshot_20230804-021131_Settings](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/3f3f310c-39c9-4b34-9f23-bd062804da81)

**Comment by ryanrudolfoba** [comment]
This is also documented in the FAQ Q0 -

![Screenshot_20230805-220958](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/3dc96b79-da2c-4b44-93b7-f66bc408980d)

**Comment by ryanrudolfoba** [comment]
Havent heard back. Closing this issue. Make sure ext ssd is setup as GPT if using Windows to Go.
