### ISSUE TITLE
System ERROR in install

### ISSUE THREAD

**Issue by shuxnhs** [ryanrudolfoba/SteamDeck-Clover-dualboot#22]
can you help me, i have meet this error in installing...

Scanning the drive for archives:
         
ERROR: No such file or directory
Clover-5154-X64.iso.7z

System ERROR:
Unknown error -2147024894
Error mounting ISO!
umount: /home/deck/temp-clover: not mounted.

**Comment by eXoenix** [comment]
I had this issue when I was in the steam recovery section, and not booted into the steam deck os on the device.

**Comment by ryanrudolfoba** [comment]
Hi you should do the steps on SteamOS desktop mode.

Please reboot out of recovery mode, and reboot SteamOS to game mode. Once in game mode, go to Desktop mode then perform the steps in the github.

**Comment by ryanrudolfoba** [comment]
Haven't heard back so i would assume that the steps I've outlined has helped you.

 Please feel free to re-open this issue if you are still having difficulties with the clover install script and i will try my best to help.

**Comment by shuxnhs** [comment]
After restarting my steamdeck, i install clover successful. Thans for your help!
