### ISSUE TITLE
Method To Update? 

### ISSUE THREAD

**Issue by ccsnet** [ryanrudolfoba/SteamDeck-Clover-dualboot#24]
Hi... Is there a me this to update if clover is already installed and you release a patch or even new theme?

Faq doesn't call any options out be it manual or automatic.

Thanks

Terran

**Comment by ryanrudolfoba** [comment]
to update please uninstall the old version first, clone the repo to get the new version then install it.

i will update the FAQ to have this information. thank you for pointing it out.

**Comment by ccsnet** [comment]
Thanks... Would it be possible to build in to the app?

Thanks

T

**Comment by ryanrudolfoba** [comment]
I dont know the best way to plement the update. For now it is a manual process.

To update to new version of Clover -
* Go to Desktop Mode and open Clover Toolbox
* Select uninstall
* clone the github repo to get the latest version
* install clover

**Comment by ryanrudolfoba** [comment]
To update to new version of Clover -

Go to Desktop Mode and open Clover Toolbox
Select uninstall
clone the github repo to get the latest version
install clover
