### ISSUE TITLE
Doesn't work with ChimeraOS

### ISSUE THREAD

**Issue by bt61** [ryanrudolfoba/SteamDeck-Clover-dualboot#25]
I understand this isn't a supported use, but it's so similar I'm hoping it could become supported.  I have Win10 and ChimeraOS (a SteamOS project) in my small Dell desktop, each installed on separate SSDs.  When I run through the steps, it's lets me choose default OS, then the install fails;

`Sudo password is good!`
`1st sanity check. So far so good!`
`-/install-Clover.sh: line 45: efibootmr: command not found rEFInd is not detected! Proceeding with the Clover install.`
`SteamoS`
`-/install-Clover.sh: line 101: /usr/bin/7z: No such file or directory`
`Error mounting ISO!`
`umount: /home/gamer/temp-clover: not mounted. `
`[gamer@chimeraos SteamDeck-Clover-dualboot]$`

Any chance this is an easy fix and this project can extend its usefulness to ChimeraOS desktop users?

**Comment by ryanrudolfoba** [comment]
Yes it doesnt work with ChimeraOS. I tried to make it work sometime ago but ChimeraOS is missing several binaries needed by the script.

**Comment by ryanrudolfoba** [comment]
Script only works when running on SteamOS. No future plans to port to ChimeraOS as there are several binaries missing in ChimeraOS.
