### ISSUE TITLE
Can't install on BAZZITE OS

### ISSUE THREAD

**Issue by onetidd** [ryanrudolfoba/SteamDeck-Clover-dualboot#26]
Hello i was using your script on my steamdeck on steam os for triple boot (Batocera, windows and steamos) and all worked nice.
Now i would like to switch to bazzite OS (Fedora38) but i can't get pass the message "Sudo password is blank ..." everytime it asks to change the password but nothing happen.

Thanks in advance.

**Comment by ryanrudolfoba** [comment]
This script only works when being run on SteamOS. Although I am interested in Bazzite too once I have some free time I'll start to port it to Bazzite.

**Comment by schabpiotr** [comment]
I'm also interested in installing clover alongside Windows and BazziteOS. As Bazzite can be installed on standard Laptops and Desktops it will be a great addition when installed on a standard PC instead of GRUB, not only on a handheld PC like SteamDeck.

**Comment by ryanrudolfoba** [comment]
Yes I will start poking around on this. Just a heads up my testing will be mostly on Steam Deck or with PCs that have secure boot disabled.

There are extra steps needed for Clover to work on secure boot PCs.

**Comment by DaVinylSmith** [comment]
I know this is an old issue, but for anybody curious, I was able to get the installation process working with bazzite by replacing all references of '/esp/efi' to '/boot/efi/EFI' in install-Clover.sh & install-clover.sh

I have not tested Clover-toolbox yet

**Comment by ryanrudolfoba** [comment]
Sorry this has taken a while. Started to add logic to the script so it can detect if its running on SteamOS or Bazzite.

Need a bazzite icon so it matches with the theme.

Here's a quick look if anyone is interested -

![image](https://github.com/user-attachments/assets/8579df4a-ea55-4994-a1cf-1284a9738371)

**Comment by Goldenfreddy0703** [comment]
Hey @ryanrudolfoba , Thank you very much for looking into this. I'm on Bazzite and i recently just installed Windows to my Steam Deck if you could get this script working soon, that would be amazing. 

Thank you very much!!!!

**Comment by naanlizard** [comment]
> I know this is an old issue, but for anybody curious, I was able to get the installation process working with a bazzite/windows dual boot by replacing all references of '/esp/efi' to '/boot/efi/EFI' in install-Clover.sh & install-clover.sh
> 
> EDIT: I managed to get Clover-Toolbox working as well by doing the same thing to Clover-Toolbox.sh under 1Clover-tools once the installation process has completed

To add to this, because my username wasn't deck, I had to change `deck:deck` to `myusername:myusername` in custom/clover-bootmanager.service

**Comment by ryanrudolfoba** [comment]
> > I know this is an old issue, but for anybody curious, I was able to get the installation process working with a bazzite/windows dual boot by replacing all references of '/esp/efi' to '/boot/efi/EFI' in install-Clover.sh & install-clover.sh
> > EDIT: I managed to get Clover-Toolbox working as well by doing the same thing to Clover-Toolbox.sh under 1Clover-tools once the installation process has completed
> 
> To add to this, because my username wasn't deck, I had to change `deck:deck` to `myusername:myusername` in custom/clover-bootmanager.service

for bazzite the default will be bazzite:bazzite

the script is composed of 3 components -

main install script \
clover-bootmanager.service / clover-bootmanager.sh \
Clover-Toolbox.sh

main install script is done but then i figured might as well add the etc whitelist for SteamOS so it is ready once 3.6 goes to Stable.

clover-bootmanager.service / clover-bootmanager.sh is done.

Clover-Toolbox.sh i havent looked into yet. this needs a minor rework especially the uninstall part.

**Comment by ryanrudolfoba** [comment]
Clover script has been updated you can now use this on both Bazzite and SteamOS.

Install it using install-clover.sh

Let me know how it goes.

**Comment by Goldenfreddy0703** [comment]
Hey, I installed your script and it works very well and I'm able to switch between bazzite and windows. One small problem I noticed in the clover tool box was that the pre-installed themes did not show for me but they did however showed in the configuration gui.

**Comment by ryanrudolfoba** [comment]
> Hey, I installed your script and it works very well and I'm able to switch between bazzite and windows. One small problem I noticed in the clover tool box was that the pre-installed themes did not show for me but they did however showed in the configuration gui.

fixed. please clone the repo to get the latest version.

**Comment by ryanrudolfoba** [comment]
Closing this now - installer script has been updated to work for Bazzite / SteamOS.

**Comment by Goldenfreddy0703** [comment]
Hey @ryanrudolfoba , im very sorry to ping you and i didn't want to make an issue post but a few days ago i was doing a little bit more testing with clover and i found out the the Timeout Option wasn't either applying or working. I set the timeout to any number and click ok and exit the clover toolbox and reboot and the timeout was not showing nor counting down. If you could look into this, that would be great.

Thank you

**Comment by schabpiotr** [comment]
> Hey @ryanrudolfoba , im very sorry to ping you and i didn't want to make an issue post but a few days ago i was doing a little bit more testing with clover and i found out the the Timeout Option wasn't either applying or working. I set the timeout to any number and click ok and exit the clover toolbox and reboot and the timeout was not showing nor counting down. If you could look into this, that would be great.
> 
> Thank you

Unfortunately I think it's an Clover issue directly, so it's not ryan's script that is the problem. I had installed clover after my first comment on this "issue" with BazziteOS with customizing the script before DaVinylSmith commented on how to (and these are the only modifications I did, also with changing the username:group to schabik:schabik as I use it as default) but the timeout doesn't work since then.

**Comment by ryanrudolfoba** [comment]
try thia please -

`sudo blkid | grep nvme0n1p1 `

**Comment by Goldenfreddy0703** [comment]
Hey sorry i  never got back to you but i did what you said, here is a log 

```
jenki@bazzite:~$ sudo blkid | grep nvme0n1p1
[sudo] password for jenki: 
/dev/nvme0n1p1: LABEL_FATBOOT="esp" LABEL="esp" UUID="F551-844B" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="EFI System Partition" PARTUUID="8b8b7d31-6879-4358-a58e-21fef58ff1bb"
jenki@bazzite:~$ sudo blkid
/dev/nvme0n1p3: LABEL="bazzite-deck_fedora" UUID="988422a5-5ccd-4fc8-badb-bc54e5bf90b9" UUID_SUB="99d5d690-d7ac-46be-9b81-828ed01a295b" BLOCK_SIZE="4096" TYPE="btrfs" PARTUUID="a359a84a-f455-4ce7-99c3-ee9f57aa3cc1"
/dev/nvme0n1p1: LABEL_FATBOOT="esp" LABEL="esp" UUID="F551-844B" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="EFI System Partition" PARTUUID="8b8b7d31-6879-4358-a58e-21fef58ff1bb"
/dev/nvme0n1p4: BLOCK_SIZE="512" UUID="2666C9661C0EC60E" TYPE="ntfs" PARTUUID="607a0c71-13c2-49ab-ac6b-742aaea2f2a9"
/dev/nvme0n1p2: UUID="4d382d42-c31b-48f9-8a3c-eaecf1c77bbf" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="ac48824d-1de2-4e93-87db-2e1e7023f912"
/dev/mmcblk0p1: UUID="4471aa91-1bf2-4278-8386-4950069f2d52" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="1958027e-0927-4ce9-b5cb-d49e744b49ba"
/dev/zram0: LABEL="zram0" UUID="809c0f40-f207-4013-b898-69a4aabb94ce" TYPE="swap"

```

Hopefully this helps
