### ISSUE TITLE
Themes not loading on Bios 118 Steam OS 3.5

### ISSUE THREAD

**Issue by hartojodylan** [ryanrudolfoba/SteamDeck-Clover-dualboot#28]
![ss](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/94948082/98fd853c-3194-44a8-9ab4-91bb94708b4c)
As shown here, theme list only shows as time and when selected it doesn't change the theme and starts up with the default no theme of clover

**Comment by ryanrudolfoba** [comment]
I just pushed a new update to fix this.

Please uninstall clover, clone the repo again to get the latest version then perform the install.

**Comment by hartojodylan** [comment]
fixed! huge thanks
