### ISSUE TITLE
The dual boot page doesn’t show up 

### ISSUE THREAD

**Issue by 2Tiked8** [ryanrudolfoba/SteamDeck-Clover-dualboot#29]
The steam deck don’t show up the clover screen anymore and I don’t know why I didn’t anything end it doesn’t work anymore but the operating systems function as normal only the clover screen is gone anyone has a fix?

**Comment by ryanrudolfoba** [comment]
Try manually reboot to SteamOS and the script will fix it automatically.

Turn off the Steam Deck.
While powered off, press voldown + power
Select boot from file, esp > efi > steamos > steamcl.efi
Wait until it boots to game mode
Reboot and it will go back to Clover

**Comment by ryanrudolfoba** [comment]
havent heard back so closing this issue. please re-open as needed.
