### ISSUE TITLE
GUI Tuning -> Pointer Speed Not saving after Restart

### ISSUE THREAD

**Issue by cokybv** [ryanrudolfoba/SteamDeck-Clover-dualboot#3]
It's really awesome that we have this feature in Clover's Settings menu and it does work for that instance when you change the default value from 04 to something like 09 you can feel and see the cursor move further, however this new value is not saved after you restart. It goes back to its default value and I couldn't find any option to save the changes that I've made.

**Comment by ryanrudolfoba** [comment]
afaik when making changes from Clover's settings menu it is like a "preview" and changes wont be saved automatically. need to manually edit the config file to make it persistent.

i've updated the config.plist to have the mouse pointer speed at 20. i've tried this on my machine and it works good i can easily use the trackpad to control the mouse pointer to select which OS to boot from.
