### ISSUE TITLE
Line 101 7z iso issue

### ISSUE THREAD

**Issue by phild2gb** [ryanrudolfoba/SteamDeck-Clover-dualboot#31]
Hi, I can't get past stage 1, I get the attached error for line 101 folder not found, any advice would be great.

![20231015_182131](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/85587389/a099cef5-58e0-47b3-b55d-b9bccea67cb3)

**Comment by ryanrudolfoba** [comment]
That's strange as 7z is bundled on SteamOS.

What version steamOS are you on?

Do this in konsole and paste output here -

cat /etc/os-release
whereis 7z
which 7z

**Comment by ryanrudolfoba** [comment]
Based on your screenshot you are using SteamOS 3.1 which is really really old.

Just to clarify, are you trying to do this on SteamOS Desktop Mode? Or are you doing this from the recovery image? Make sure you are doing this on SteamOS Desktop Mode.

**Comment by phild2gb** [comment]
Thank you, it's in desktop mode, I downloaded the image from steam when I got the new SSD, in that case I'll try and update my deck.

Thanks again

**Comment by phild2gb** [comment]
Started from scratch, all went perfectly.

Thanks again

**Comment by ryanrudolfoba** [comment]
latest script now checks for the presence of 7z binary. 

if the 7z binary doesnt exist it displays a message to update the SteamOS first.
