### ISSUE TITLE
Clover Windows 11 only and no theme from install

### ISSUE THREAD

**Issue by J-Dudson** [ryanrudolfoba/SteamDeck-Clover-dualboot#32]
I installed clover with both Windows 11 and SteamOS on same SSD. Worked fine and now when I restart my device to change OS I only get Windows 11 and no theme. I reinstalled clover, and it worked however it reset back to this after another restart. 
I can get back into steam os using the efi in esp.

![16976767646885210913965116972499](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/148404431/e94898dc-0caf-4879-a51d-aad8019d6958)

**Comment by ryanrudolfoba** [comment]
Boot to SteamOS and then go to Desktop Mode.

On the desktop launch the item called Clover Toolbox and then select the item called Status. Paste the results here.

**Comment by ryanrudolfoba** [comment]
havent heard back so i'll be closing this. feel free to re-open if need further help.
