### ISSUE TITLE
Can't enter clover

### ISSUE THREAD

**Issue by lamlam77777** [ryanrudolfoba/SteamDeck-Clover-dualboot#33]
![20231019_134520](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/10419307/26739ad9-1108-4080-8f13-5c21dc3a2675)
Now bootup the deck will enter windows
Need volume - + power to enter clover

**Comment by ryanrudolfoba** [comment]
Sorry for the late reply.

Turn off the Steam Deck. While off, press voldown + power then select SteamOS. The script will fix the dual boot automatically and make Clover the top priority.

Please let me know if this helps.

**Comment by lamlam77777** [comment]
I try before post and it can’t fix

**Comment by ryanrudolfoba** [comment]
go to desktop mode and launch Clover Toolbox. Select the uninstall option.
Once it is uninstalled, clone the repo again to get the latest version and try to install it.

BTW is Windows installed on sdcard / external SSD, or on the internal SSD?

**Comment by ryanrudolfoba** [comment]
Havent heard back so i'll close this. Please feel free to re-open if issue persists and i will try my best to help
