### ISSUE TITLE
Clover boot menu does not load when choosing Restart

### ISSUE THREAD

**Issue by JeramZz** [ryanrudolfoba/SteamDeck-Clover-dualboot#36]
Hi,

First of all thank you for this script.
But I'm having issues with it when restarting SteamOS or Windows. The boot menu does not appear, only black screen.

I am only able to see the boot menu when turning on the steam deck after a complete shutdown.
I previously use reFind which broke after SteamOS update, so I decided to give clover a try.
I did not do any cleanup of the previous refind installation. Could that have caused this restart issue I'm having?

Thank you for your time.

**Comment by ryanrudolfoba** [comment]
I've push an update to the script that includes a newer clover efi release 5156. Please check if that fixes your issue.
