### ISSUE TITLE
Suggestion/Issue? SD Card booting. 

### ISSUE THREAD

**Issue by digimancer** [ryanrudolfoba/SteamDeck-Clover-dualboot#37]
Not sure if an issue or a suggestion... Ran this installer in combination with your SteamOS on SD script (which is lovely ty), and it created the files on the SD card, but it still always defaults to the SteamOS efi when booting. I can manually select it in the Decks boot menu, but again, on the NVME it defaults to the Windows EFI, and on the SD card it defaults to the SteamOS, and neither start Clover.
Oh another weird quirk to installing via SD, I never got the Clover-Toolbox desktop shortcut.

**Comment by ryanrudolfoba** [comment]
Sorry for late reply. I've only tested this script for SteamOS installed on the internal SSD. This wont work properly when SteamOS on sdcard.
