### ISSUE TITLE
Custom splash screen only when booting windows.

### ISSUE THREAD

**Issue by Musicislife6984** [ryanrudolfoba/SteamDeck-Clover-dualboot#38]
Is it possible to only have a custom splash screen when booting windows? I really like this option from the previous version

**Comment by ryanrudolfoba** [comment]
The previous option was using a 3rd party app - HackBGRT. That app is awesome as you can customize the BGRT logo when Windows boots up.

I moved away from HackBGRT as I want the script to have few dependencies from 3rd party app. Right now clover script is purely bash script and only uses Clover EFI.

You can change the logo (BGRT) but that will reflect on all. Or you can remove the logo and have it use the default. Launch Clover Toolbox and select the LOGO option.

**Comment by ryanrudolfoba** [comment]
Closing this issue as I don't want to re-add HackBGRT. I want the script to remain purely bash and not depend on 3rd party apps
