### ISSUE TITLE
Is there an option to remap Clover?

### ISSUE THREAD

**Issue by hlebushekhub** [ryanrudolfoba/SteamDeck-Clover-dualboot#39]
I use XYAB (Switch layout) on Steam Deck, so my main button is B, but Clover use standard method with A being the main button. Is there any way to remap Clover?

**Comment by ryanrudolfoba** [comment]
Hi sorry for late reply. The Steam Deck controller also acts as a basic keyboard - A is  ENTER and B as ESCAPE. You would need a program outside of Clover to remap this.
