### ISSUE TITLE
Still showing Boot image

### ISSUE THREAD

**Issue by zeluisrz** [ryanrudolfoba/SteamDeck-Clover-dualboot#40]
Hi, I uninstall clover. But still showing boot image "powered by clover". How can repair this?

**Comment by ryanrudolfoba** [comment]
sorry for late reply.

Make sure to uninstall clover via the Clover Toolbox.

If the custom logo still shows up, go to desktop mode, open konsole terminal and let me know the output of this

sudo su
cd /esp/efi/steamos
ls

**Comment by ryanrudolfoba** [comment]
If you need further help please feel free to reopen this case or create a new one.
