### ISSUE TITLE
Batocera on SD Card sometimes disappears from boot menu after restarting

### ISSUE THREAD

**Issue by joshbt** [ryanrudolfoba/SteamDeck-Clover-dualboot#41]
I have a 2TB internal drive installed on my LCD Steam Deck. Windows and SteamOS are loaded on separate partitions on the internal drive, and Batocera is loaded on my 1TB SD card.

There is one small issue: if SteamOS or Batocera are the last OS's running, then upon reboot, Batocera will suddenly not be listed at all on the boot screen.  I can boot into SteamOS or Windows, but Batocera isn't even an option. 

If I boot into Windows, then reboot the deck, now Batocera will be listed again. It does not come back if I then boot into SteamOS or Batocera then reboot, no matter how many times I try, 

When I shut down from any of the OS's completely, then I will see all three options every time upon powering back on.

Also according to [this reddit thread](https://www.reddit.com/r/WindowsOnDeck/comments/181icl9/odd_issue_with_clover_that_i_havent_seen_come_up/) - if you use Batocera from the USB C port, it shows up on the next reboot either from SteamOS, Windows or Batocera.

Any thoughts on how to fix this?

**Comment by ryanrudolfoba** [comment]
sorry for late reply. that reddit thread is from me also which points out that the Steam Deck sdcard could be at fault as batocera on the USB C port works OK. workaround is to shutdown the Steam Deck so the sdcard gets reinitialized and Clover will see it.

**Comment by ryanrudolfoba** [comment]
This is now fixed on latest BIOS update! My hunch is correct all along that its a firmware issue.
