### ISSUE TITLE
Incompatibility / crash with certain USB keyboard

### ISSUE THREAD

**Issue by joshbt** [ryanrudolfoba/SteamDeck-Clover-dualboot#42]
This particular keyboard remote is not compatible with Clover. It's called "Pepper Jobs W10".
I have a Steam Deck with dual boot setup just fine. Whenever this USB dongle for the remote is connected Clover will crash. Upon startup it never reaches the boot screen when connected. If I disconnect it and then reach the boot screen and then connect the USB dongle, Clover will instantly freeze up and no input is recognized.
I've tried the remote USB dongle with two different USB-C hubs with the exact same outcome. I've tried it with nothing else connected on the hub except for the dongle. Other USB keyboards I have work just fine but not the Pepper Jobs one.

**Comment by ryanrudolfoba** [comment]
Sorry i have no control over this. As there are a lot of hardware devices out there, there's a chance that some hardware are incompatible.

**Comment by ryanrudolfoba** [comment]
I've push an update to the script that includes a newer clover efi release 5156. Please check if that fixes your issue.
