### ISSUE TITLE
Windows boots into bluscreen when an external monitor is connected

### ISSUE THREAD

**Issue by SuperSailorMoonR** [ryanrudolfoba/SteamDeck-Clover-dualboot#43]
When selecting Windows it boots always into a bluscreen with a qr code when my external monitor is connected through a Jsaux docking station.
Clover is also displayed in portrait mode and not in landscape mode on my external monitor.

It works fine when I disconnect the monitor and boot into windows and then connect the monitor when windows is up an running.

Without the external monitor clover works fine, both steamos and windows.

I looked if a memory.dmp file is created in windows but there isn´t one.

I think the problem could related to the portrait mode?

I can try is using another usb c docking station or another monitor and see if the problem persists, it this would be helpfull?

**Comment by ying27** [comment]
I can confirm that this issue also happens with the official Steam Deck dock from Valve. Not sure what is causing this issue as I had 0 issues in the past when I was not using Clover.

**Comment by ryanrudolfoba** [comment]
Sorry for late reply. If the external display is more than 1080p it will get displayed as portrait mode. This is related to Steam Deck screen which is native portrait.
Could be a compatibility issue with the dock. I'm using a baseus dock connected to 1080p samsung TV. Works fine using Win10 / Win11 / Batocera and SteamOS.

**Comment by SuperSailorMoonR** [comment]
Np u have a live too. Yes, I can confirm, that I use a display with higher resolution than 1080p, in fact I do not have a dispaly with 1080p or lower they all are 1440p or 2160p. I tried another monitor higher than 1080p same probelm.

I know that the steam decks display is native portrait not landscape.

It has to be a clover problem, because if I use the build in boot menu (vol. down + power button) Windows ist booting fine with an external display connected, I get the bluescreen only when booting with clover.

Strange is that Windows does not create a dmp file, I think the bluescreen happens to early while still loading services etc. so logging ist not running yet?

**Comment by ying27** [comment]
FYI I updated to the latest release and so far the BSOD are gone!

**Comment by SuperSailorMoonR** [comment]
that was fast, will try myself an leave feedback here.

**Comment by SuperSailorMoonR** [comment]
sadly no luck here, still bluescreen with newest build of clover, when booting into windows with 1440p display attached.

**Comment by ying27** [comment]
I am using it with my TV (4K) and so far, seems to be working fine. One thing I discovered now is if my Steam Deck was off, it boots to Windows with no issues. If I try to reboot from Windows, I do get a BSOD.

**Comment by SuperSailorMoonR** [comment]
Will try fresh boot and reboot.

**Comment by SuperSailorMoonR** [comment]
Can confirm, on fresh boot no bluescreen, on restart bluescreen.

**Comment by ryanrudolfoba** [comment]
maybe need to downgrade to an older version of the Clover EFI.
i can't replicate this issue on my OLED and LCD, so please try this steps -

clone the repo
edit install-Clover.sh
on line 5, change 5156 to 5155
![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/3479f6b0-f932-40b2-b085-f6321ef09662)

save the file and then run ./install-Clover.sh
if that doesnt work, uninstall Clover, repeat the steps and use 5152

**Comment by ryanrudolfoba** [comment]
havent heard back hopefully my suggestions of downgrading to an older Clover EFI worked.

ive also updated the script today to include Clover 5157. Feel free to re-open the case for any issues.
