### ISSUE TITLE
Rescuezilla installed on usb stick not recognised.

### ISSUE THREAD

**Issue by mikmikmikmik** [ryanrudolfoba/SteamDeck-Clover-dualboot#45]
Although I can make rescuezilla iso work under ventoy, when installing it via balena, the usb stick is not seen by clover upon reboot.
VOL+ PWR and boot icon sees it as  Linpus or somesuch and can boot from the stick then.

Also, if 2x Ventoy sticks are plugged in, it is a bit difficult to see which stick is which. Any way they can be differentiated in your script?

Thanks.

**Comment by ryanrudolfoba** [comment]
sorry i tried but cant figure out the Rescuezilla.

it creates 4 partitions and the 2nd partition contains the EFI files for it to boot. I tried to update the Clover config.plist to reflect this but for some reason it is not working.

i would suggest use Ventoy for Rescuezilla.

if you have multiple Ventoy sticks plugged in then Clover will detect all of them and give them the same name and icons. This is working as intended.
