### ISSUE TITLE
Also Asked in Facebook

### ISSUE THREAD

**Issue by mikmikmikmik** [ryanrudolfoba/SteamDeck-Clover-dualboot#47]
Is there a script or something available so that when windows updates and replaces the bootloader, that when logged into windows, I can run the script which will get the clover boot menu back again, instead of me having to search for steamcli.efi to execute on first post windows patch bootup?

Thanks.

**Comment by ryanrudolfoba** [comment]
Sorry for late reply. Look at the OPTIONAL section of the README -

https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot#optional---scheduled-task-for-windows-use-this-only-if-you-have-windows-installed-on-microsd--external-ssd-and-if-windows-keeps-hijacking-the-bootloader

It will be a scheduled task on the Windows side so once you set it up its all automatic.

**Comment by mikmikmikmik** [comment]
I'll Sure have a look at that. Thank you.
