### ISSUE TITLE
Possibility?

### ISSUE THREAD

**Issue by mikmikmikmik** [ryanrudolfoba/SteamDeck-Clover-dualboot#48]
Clover shows on ext monitor on switch on, boots auto into steamdeck os. No display on either ext monitor or deck even with ext monitor lower res option enabled in steam settings.
Have to unplug hdmi, hold pwr down until I think it is off, switch it on again so clover boots into deck again, and thrn plug ext monitor in again.
Also sometime clover boots into ext monitor screen at lower resolution.

Thanks for all you great work.

**Comment by ryanrudolfoba** [comment]
sorry for late reply.

> Clover shows on ext monitor on switch on, boots auto into steamdeck os. No display on either ext monitor or deck even with ext monitor lower res option enabled in steam settings.

this sounds like a SteamOS issue. uninstall clover and observe if you still have the same issue.

**Comment by ryanrudolfoba** [comment]
If you need further help please feel free to re-open or create new issue request
