### ISSUE TITLE
Windows to go boot option for sd card when there is no windows to go installed on it

### ISSUE THREAD

**Issue by Igilq** [ryanrudolfoba/SteamDeck-Clover-dualboot#49]
Hello, I have installed your script (which helps me alot) and when I launch my steam deck it shows three options instead of two, steam os, windows on ssd and windows to go on sd card. Out from curiosity I decided to check what would happen if I chose windows on sd card, after choosing it, it booted to windows on ssd

**Comment by ryanrudolfoba** [comment]
That happebs when there is a Windows update. Please reboot to SteamOS and the script will fix it automatically.

**Comment by ryanrudolfoba** [comment]
no need it will fix it automatically. when you reboot it should be fixed.

**Comment by Igilq** [comment]
Issue got fixed. Thanks for help
