### ISSUE TITLE
Experimental 

### ISSUE THREAD

**Issue by akeilox** [ryanrudolfoba/SteamDeck-Clover-dualboot#5]
I had fresh install of Windows and SteamOS on steamdeck which shares a 1TB disk 50% 50% and batocera on SD card.

Simply cloning the script and running the following experimental script gave me boot select;
chmod +x experimental-install-Clover.sh
./experimental-install-Clover.sh

No need to mess with Windows Scheduler etc. 
Unless I am not missing anything else this is brilliant, thank you very much good sir for the brilliant work!

BTW: tried running the following command in Windows 10 CMD with Administrator rights opened gives me "The boot configuration data store could not be opened. Access is denied":
bcdedit.exe -set {globalsettings} highestmode on

**Comment by ryanrudolfoba** [comment]
Yes experimental is what ive been using too as its much easier and quicker to setup.

For the bcdedit command, access denied means it didnt got admin rights. Open up CMD again and make sure run it as administrator, then do the bcdedit command again.

**Comment by ryanrudolfoba** [comment]
Manually boot back to SteamOS -

boot from file > esp > efi > steamcl.efi

Once its back in game mode, power off the Steam Deck then power it back on. It should automatically fix itself and Clover will show up.

**Comment by akeilox** [comment]
I tried booting with Steam Recovery USB (in the hopes of recovering from there) and it stucks at the Steam logo.
Is this something you encountered before too? i.e. Steam Recovery iso not booting up.
I have custom installs under steamos which took a while to configure, wondering alternative ways to just wipe it._

**Comment by ryanrudolfoba** [comment]
For steamos recovery usb make sure you are using at least a usb3.0 drive. 

Its overkill i use a spare external 256GB ssd for my steamos recovery drive and gets the job done quickly.
