### ISSUE TITLE
Clover only sees Batocera USB by doing a complete shutdown or when rebooting after being in windows. 

### ISSUE THREAD

**Issue by peterlouvel** [ryanrudolfoba/SteamDeck-Clover-dualboot#50]
Clover only sees Batocera USB after doing a complete shutdown or when rebooting after being in windows, not when doing a rebooting from steamOS or gamemode.

**Comment by ryanrudolfoba** [comment]
This is similar to this -

https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/issues/41

**Comment by ryanrudolfoba** [comment]
This is now fixed on latest BIOS update! My hunch is correct all along that its a firmware issue.
