### ISSUE TITLE
Clover causing steam deck on windows to wake up

### ISSUE THREAD

**Issue by Igilq** [ryanrudolfoba/SteamDeck-Clover-dualboot#51]
Hello, I found another issue. Sometimes I leave at night steam deck in sleep mode. And while it is booted into windows, it causes steam deck to wake up and also sometimes me. How can I fix this?

**Comment by thidguy** [comment]
Pretty sure it was a bios issue or something because I've had the same problem with it in steam os

**Comment by ryanrudolfoba** [comment]
sorry for late reply. this doesnt sound Clover related at all. uninstall Clover and observe if you still have the issue on Windows.
