### ISSUE TITLE
Arch boot option

### ISSUE THREAD

**Issue by Musicislife6984** [ryanrudolfoba/SteamDeck-Clover-dualboot#52]
Can you add a boot option for Arch?

**Comment by Musicislife6984** [comment]
EFI/BOOT/BOOTX64.EFI

**Comment by Musicislife6984** [comment]
EFI/BOOT/BOOTX64.EFI


Sean Martz

**Comment by Musicislife6984** [comment]
I was having issues with that boot loader, so I switched to grub. The grub one is grub\x86_64-efi\grub.efi

**Comment by ryanrudolfoba** [comment]
sorry for late reply. this is where you would need to make the edits in config.plist -
![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/6dc34797-1335-40a5-beba-f43e840742be)

i'm confused on the path that you gave me. please double check or better provide a screenshot.
