### ISSUE TITLE
Removed Steam OS boot loader and only left Windows Boot Loader on Uninstall

### ISSUE THREAD

**Issue by xaniel123** [ryanrudolfoba/SteamDeck-Clover-dualboot#54]
I uninstalled Clover and lost the ability to boot it to Steam OS. I restored my boot option by following this guide from Medium. It would be nice if the uninstall process restored all of the boot options instead of just one. 

https://medium.com/@vincentbiasa6767/how-to-restore-steamos-boot-entry-after-installing-a-new-steamos-updates-c03e1273656d

**Comment by ryanrudolfoba** [comment]
sorry for late reply. i uninstalled Clover on both my Steam Deck OLED / LCD and it works as it should.

The Clover EFI entry disappeared, and the SteamOS and Windows EFI entries are present. It defaults to boot back to Windows.
