### ISSUE TITLE
Stuck on clover boot screen

### ISSUE THREAD

**Issue by doomshreal** [ryanrudolfoba/SteamDeck-Clover-dualboot#58]
If I don't click fast enough the logos disappear and I am left with a blank screen with just the background and logo.  If I do manage to click one in time it goes to the same screen.

I cleared CMOS to see if that would help as it was similar to another users issue and that worked for them but it didn't fix the problem.

Below is a the last part of my script.  It looks different from what I've seen in the pictures and video.

Everything is Ok

Size:       8617984
Compressed: 1922072
[sudo] password for deck: 2nd sanity check. ISO has been mounted!
3rd sanity check. Clover has been copied to the EFI system partition!
cp: cannot stat '/esp/efi/Microsoft/Boot/bootmgfw.efi': No such file or directory
Final sanity check. Clover has been successfully installed to the EFI system partition!
Desktop icon for Clover Toolbox has been created!

**Comment by doomshreal** [comment]
I did some investigating and if I boot while my computer screen isn't plugged in, I have no problems.  But if I try to boot with it connected I have the issue I described above and it won't automatically go to the OS I picked after 15 seconds.

**Comment by ryanrudolfoba** [comment]
sorry for late reply. please try uninstall / reinstall Clover using the Clover Toolbox script.

**Comment by ryanrudolfoba** [comment]
If you need further help please feel free to re-open or create new issue request
