### ISSUE TITLE
Mohave theme not persisting after reboot/shutdown

### ISSUE THREAD

**Issue by SpazShark** [ryanrudolfoba/SteamDeck-Clover-dualboot#6]
When I go to the options screen on the boot loader, I see three options under theme from top to bottom: embedded (selected), Catalina, and Mohave.

I select Mohave and back out to the boot selection menu. The theme now reflects the 'Mohave' theme.

If I reboot or shutdown the Steam Deck, when I return to the boot loader screen it's back to the 'Catalina' theme and when I check in the options 'embedded' is selected. 

Any ideas on how to make the Mohave theme persist through subsequent boots? I have SteamOS installed to my SSD, Windows to Go installed on a MicroSD, and I installed clover via your experimental script.

**Comment by ryanrudolfoba** [comment]
It wont persist. The default behavior is that it will do a random theme on each reboot.

If you want just the Catalina theme, follow the steps in How To Add / Remove Themes -

https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot#how-to-add--remove-themes


I added the default 2 themes so user can choose to keep it random or delete the one they dont like.

**Comment by SpazShark** [comment]
> It wont persist. The default behavior is that it will do a random theme on each reboot.
> 
> If you want just the Mojave theme, follow the steps in How To Add / Remove Themes -
> 
> https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot#how-to-add--remove-themes
> 
> I added the default 2 themes so user can choose to keep it random or delete the one they dont like.

I completely understand now. Thanks for explaining this!
