### ISSUE TITLE
Kali Linux issue

### ISSUE THREAD

**Issue by paryska99** [ryanrudolfoba/SteamDeck-Clover-dualboot#62]
Kali Linux is supported as listed by clover dual boot, but I don't know what is meant by that.
Did you actually manage to launch an installed and not live booted Kali correctly?

After Kali Linux install and passing through clover then grub launches and then Kali through grub. Amd driver cannot load on an installed instance of Kali on my end if it launches through grub and that seems to be the only way to launch.

Does this dual boot clover repo mean support for Kali Live instead?

**Comment by ryanrudolfoba** [comment]
> Kali Linux is supported as listed by clover dual boot, but I don't know what is meant by that.

It means that if you have Kali installed on the internal SSD, the Clover GUI menu will automatically pick it up and display it on the GUI menu as a boot option.

![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/3b243da5-6f17-44c1-93b7-317e0d2b711e)

This was working last year or so, it could be newer Kali installs behave differently now.

You can edit the config.plist and find the entry for Kali and update it to point to the correct EFI file. Currently its is configured like this -

![Screenshot_20240512-102806](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/8234331d-9617-4d57-8d01-ad3c5533c2b8)

**Comment by paryska99** [comment]
Thank you, turns out the issue was on my end when creating bootable usb drive. Let's just say I hate windows defender
