### ISSUE TITLE
Desktop/Gamemode in menu?

### ISSUE THREAD

**Issue by 907470** [ryanrudolfoba/SteamDeck-Clover-dualboot#63]
Like the title says, I’m curious to know how difficult it would be to have two boot entries that issue the command to the OS

`steamos-session-select plasma`

and 

`steamos-session-select gamescope`

I’m not sure how much this will affect before the full system boot, but it would be awesome to skip issuing the commands in desktop mode and rebooting.

**Comment by 907470** [comment]
Okay the commands might be outdated, let me double check them

**Comment by ryanrudolfoba** [comment]
Thats not possible. 
Although you can configure Clover so that the CURRENT and PREVIOUS SteamOS rootfs you can select during bootup. This just saves you the 3dots+power button combination.
