### ISSUE TITLE
Blank screen when selecting "Return to Game Mode" Icon

### ISSUE THREAD

**Issue by spaine** [ryanrudolfoba/SteamDeck-Clover-dualboot#64]
Whenever I click Return to game mode, the device seem to be stuck at a blank screen, you can still see the backlight is on. 

Though holding the power button then pressing it again will load the dual boot menu properly.  

Just asking if there is a fix for this and is it also possible to go from steam desktop mode straight to game mode? 

Thanks

**Comment by ryanrudolfoba** [comment]
Clover is only responsible for selecting which OS to load during startup.

It is not responsible for switching between Game Mode and Desktop Mode.
