### ISSUE TITLE
Clover doesn't detect my Windows Install

### ISSUE THREAD

**Issue by dgiaffe** [ryanrudolfoba/SteamDeck-Clover-dualboot#65]
Hello, before I think of reinstalling Windows (which I already customized and downloaded what I wanted installed in), I was wondering if there is anything I could check so Clover detects my Windows installation. If I run the "STATUS" option in the Clover-Toolbox, I believe I do see the Windows Installation: 

```
Clover Boot Manager - Mon Jun 17 11:59:55 AM EDT 2024
BIOS Version : F7G0107
PRETTY_NAME="SteamOS"
VERSION_ID=3.5.19
BUILD_ID=20240422.1
Linux steamdeck 6.1.52-valve16-1-neptune-61 #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000 x86_64 GNU/Linux
no dump files. no action needed.
Clover EFI entry exists! No need to re-add Clover.
SteamOS EFI entry exists! No need to re-add SteamOS.
*** Current state of EFI entries ****
BootCurrent: 0002
Timeout: 2 seconds
BootOrder: 0002,0004
Boot0000* EFI Hard Drive (22373M51257483-Phison ESMP512GMB47C3-E13TS)
PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0)/NVMe(0x1,64-79-A7-6C-8A-30-73-49)/HD(1,GPT,d942add6-3445-49a7-8cd6-333572d59545,0
x800,0x20000)RC
Boot0001* EFI SD/MMC Card (DS 215N ﾑ/ﾵﾖ)
PciRoot(0x0)/Pci(0x1,0x3)/Pci(0x0,0x0)/SD(0)/HD(1,GPT,64328b64-1d91-4b05-8007-63335a344c5a,0x800,0x82000)RC
Boot0002* Clover - GUI Boot Manager
HD(1,GPT,d942add6-3445-49a7-8cd6-333572d59545,0x800,0x20000)/File(EFIclovercloverx64.efi)
Boot0003* Windows Boot Manager
HD(1,GPT,64328b64-1d91-4b05-8007-63335a344c5a,0x800,0x82000)/File(EFIMicrosoftBootootmgfw.efi)57494e444f57530001000
00088000000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d003
4006500370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d0000000000010000001000000004000
0007fff0400
Boot0004* SteamOS HD(1,GPT,d942add6-3445-49a7-8cd6-333572d59545,0x800,0x20000)/File(EFIsteamossteamcl.efi)
*** Current state of EFI partition ****
Filesystem   Size Used Avail Use% Mounted on
/dev/nvme0n1p1  64M  15M  50M 23% /esp
```

However, when I restart, I get only the SteamOS option 
![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/60679189/62efa244-9aa1-43fa-8f2c-d88ac4183366)

I setup the regkey for the time and bcdedit command as well. I tried re-installing the script, but no luck. I run Windows 11 on a 512 microSD and selected the Windows To Go option in Rufus and pretty sure GPT was selected since that is the default option and the only thing I changed was the Windows To Go dropdown. Any help would be appreciated, looks like a great little addition to my Steam Deck!

**Comment by ryanrudolfoba** [comment]
i made some changes the past few weeks -
![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/b3993ad6-5675-417c-a8ea-e2ddcb0f0dad)

Windows to Go sdcard is not supported anymore.

**Comment by dgiaffe** [comment]
Thank you, I was reading the troubleshooting, but didn't see the "What's New" section. I just don't want to partition my SSD or whatever. Windows runs well on my microsd but I guess I'll find another solution or just keep pressing vol down + power then. Appreciate your work though!

**Comment by ISeeTWizard** [comment]
> Thank you, I was reading the troubleshooting, but didn't see the "What's New" section. I just don't want to partition my SSD or whatever. Windows runs well on my microsd but I guess I'll find another solution or just keep pressing vol down + power then. Appreciate your work though!

That is why I didn't upgrade to the newer version of clover but staying with the old one (backed up the old version in case of reinstall)
I don't use Windows very often on my Deck and so having it on MicroSD is more than fine for me - I tried to have it on my Seagate USB-C SSD but on this one it has slow dows which I don't have on my MicroSD card

**Comment by PS2ClassicsVault** [comment]
I have this same issue but I don't have a windows to go install I have it installed via my internal SSD along side steam os

**Comment by ryanrudolfoba** [comment]
> I have this same issue but I don't have a windows to go install I have it installed via my internal SSD along side steam os

I've responded to the issue you;ve opened. Please provide the info requested.
