### ISSUE TITLE
Why was option for booting to windows on SD card removed?

### ISSUE THREAD

**Issue by Igilq** [ryanrudolfoba/SteamDeck-Clover-dualboot#68]

**Comment by ryanrudolfoba** [comment]
Running Windows on sdcard is not optimal.

Partition your internal SSD to make room for Windows, or run Windows from external SSD / USB C flash drive.

**Comment by ryanrudolfoba** [comment]
repo has been updated for Windows to GO SDCARD config.

follow this guide if you use Windows to GO SDCARD -

https://youtu.be/DPUEjOTkTDY
