### ISSUE TITLE
Unable to set steamOS as default for dual boot

### ISSUE THREAD

**Issue by julianrios** [ryanrudolfoba/SteamDeck-Clover-dualboot#69]
Using this windows setup WinDeckOS: https://github.com/Minibattle/WinDeckOS

 For some reason even though its set as default I keep booting to windows instead of clover bootloader. Both are installed as partitions on the internal drive.
 
![Screenshot_20240719_081713](https://github.com/user-attachments/assets/b3620a42-2f6e-43a1-b0c7-b28ea56ca886)

**Comment by ryanrudolfoba** [comment]
Sorry for late reply. I dont use WindeckOS. And i would assume you had to go through hoops to install it together with SteamOS.

What's most likely happening is the script is not able to disable the Windows EFI due to non-standard configuration.
