### ISSUE TITLE
Broke Windows

### ISSUE THREAD

**Issue by Scrub000** [ryanrudolfoba/SteamDeck-Clover-dualboot#70]
Installed; Broke Windows. Doesn't boot. Solution was to remove this service

**Comment by ryanrudolfoba** [comment]
Sorry for late reply. I'm sorry it didnt work out for you.

**Comment by okitaAsuka** [comment]
Perform some Windows config first! Boot to Windows and open elevated command prompt -

bcdedit.exe -set {globalsettings} highestmode on
reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\TimeZoneInformation" /v RealTimeIsUniversal /d 1 /t REG_DWORD /f
Once done, boot to SteamOS to install Clover!

你好，我碰到同样的问题了，先在windows环境下执行以上命令然后就无法进入bios选择系统了，想问下是删除哪个service才能解决？谢谢！
