### ISSUE TITLE
Latest steam update broke clover boot menu

### ISSUE THREAD

**Issue by julianrios** [ryanrudolfoba/SteamDeck-Clover-dualboot#74]
Clover boot menu not showing up on startup just boots to default steamOS

Using the clover tool box I set all my defaults again 
5 sec time
embedded theme
steamOS default

But still boots to steamOS on powerup or restart.

Need to manually use volume down and power button to pull up the clover bootmenu

**Comment by julianrios** [comment]
Clover Boot Manager - Wed Aug 7 04:13:39 PM EDT 2024
BIOS Version : F7A0131
PRETTY_NAME="SteamOS"
VERSION_ID=3.6.8
BUILD_ID=20240626.100
Linux steamdeck 6.5.0-valve12-1-neptune-65-g1889664e19fc #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 00:07:43 +0000 x86_64 
GNU/Linux
no dump files. no action needed.
Clover EFI entry exists! No need to re-add Clover.
SteamOS EFI entry exists! No need to re-add SteamOS.
Windows EFI exists! Moving it to /esp/efi/Microsoft
*** Current state of EFI entries ****
BootCurrent: 0000
Timeout: 2 seconds
BootOrder: 0000,0004
Boot0000* Clover - GUI Boot Manager	
HD(1,GPT,8637395d-0073-4bc8-b9cb-aed36a8e8243,0x800,0x20000)/EFIclovercloverx64.efi
Boot0001* EFI USB Device (JMicron Tech)	
UsbWwid(152d,901,0,000000000BF)/HD(1,GPT,93fbb59a-36ab-4199-b6d5-26a26172c5f3,0x22,0x1ffde)RC
Boot0002* EFI Hard Drive (AA240124N4001K00525-SPCC M.2 PCIe SSD)	
PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0)/NVMe(0x1,48-68-34-00-00-00-00-01)/HD(1,GPT,8637395d-0073-4bc8-b9cb-aed36a8e8243,0
x800,0x20000)RC
Boot0003* EFI USB Device 1 (JMicron Tech)	
UsbWwid(152d,901,0,000000000BF)/HD(1,GPT,93fbb59a-36ab-4199-b6d5-26a26172c5f3,0x22,0x1ffde)RC
Boot0004* SteamOS	HD(1,GPT,8637395d-0073-4bc8-b9cb-aed36a8e8243,0x800,0x20000)/EFIsteamossteamcl.efi
Boot0005* Windows Boot Manager	
HD(1,GPT,8637395d-0073-4bc8-b9cb-aed36a8e8243,0x800,0x20000)/EFIMicrosoftBootootmgfw.efi57494e444f57530001000000880
00000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d003400650
0370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d00000061000100000010000000040000007ff
f0400
*** Current state of EFI partition ****
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1   64M   42M   23M  65% /esp

**Comment by ryanrudolfoba** [comment]
Yes when the SteamOS update contains a BIOS update that can happen.

Manually reboot to SteamOS and the script will fix it automatically.

However sometimes the systemd script gets wiped during a SteamOS update, and the script wont run to fix it automatically.

Manually uninstall Clover using Clover Toolbox, and then clone the repo to get the latest version then perform the install.

Once SteamOS 3.6 goes to stable I'll implement the whitelist so that the systemd script will be more consistent during SteamOS updates.
