### ISSUE TITLE
SteamDeck is stuck on boot (Steamdeck logo + clover)

### ISSUE THREAD

**Issue by danlei88** [ryanrudolfoba/SteamDeck-Clover-dualboot#75]
I haven't used my Deck for awhile but when I plugged it in to charge it seemed to crash and then on reboot got stuck on the SteamDeck logo and a loading icon.

**Setup:** 
SteamDeck (**normal,** not OLED)
Windows 11 and SteamOS both on **internal SSD**.

When I eventually held power button to force shut down and rebooted, SteamDeck booted to the same Clover-version logo of SteamDeck but with a text saying **"Preparing automatic repair"**. After that runs through it returns a Windows 11 BSoD. Then it goes back to Clover boot selector screen and if I let it boot to my Windows SSD partition, it will once again get stuck to the boot.

I tried clearing CMOS as some github posts stated that working for them. It didn't work for me unfortunately.

I don't know how to uninstall or reinstall Clover but that was an advice I read on another ticket by the creator, Ryanrudolfoba. It's rather difficult to do anything when I can't get past the boot. I'll try getting to the SteamOS but that requires me to wait until the Windows BSoD and act fast after.

Any help of links to some possible fix guides would be appreciated! Thanks in advance!

EDIT: I reinstalled Clover but issues persist when booting to Windows. However, there's a normal SteamDeck logo this time instead of the Clover logo version. Still getting the "Preparing Automatic Repair" text when booting.

**Comment by ryanrudolfoba** [comment]
> EDIT: I reinstalled Clover but issues persist when booting to Windows. However, there's a normal SteamDeck logo this time instead of the Clover logo version. Still getting the "Preparing Automatic Repair" text when booting.

This issue is isolated to Windows. Most probably Windows got corrupted due to improper shutdown.

**Comment by ryanrudolfoba** [comment]
based on the error messages provided this issue is isolated to Windows.
