### ISSUE TITLE
Windows takes over

### ISSUE THREAD

**Issue by thanone2** [ryanrudolfoba/SteamDeck-Clover-dualboot#77]
Windows boots instead of clover no matter what I do, I've read the faq and tried everything, but nothing helps.

**Comment by ryanrudolfoba** [comment]
What SteamOS version are you on?

**Comment by ryanrudolfoba** [comment]
some questions -

Where is Windows installed? [If its on external SSD, follow this step/](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot#optional---scheduled-task-for-windows-use-this-only-if-you-have-windows-installed-on-microsd--external-ssd-and-if-windows-keeps-hijacking-the-bootloader)

What SteamOS version are you on? If you updated to SteamOS 3.6.x beta the systemd service gets wiped out and the autofix functionality doesnt work. Uninstall / reinstall Clover.

If you need further help please feel free to re-open case.

**Comment by thanone2** [comment]
> some questions -
> 
> Where is Windows installed? [If its on external SSD, follow this step/](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot#optional---scheduled-task-for-windows-use-this-only-if-you-have-windows-installed-on-microsd--external-ssd-and-if-windows-keeps-hijacking-the-bootloader)
> 
> What SteamOS version are you on? If you updated to SteamOS 3.6.x beta the systemd service gets wiped out and the autofix functionality doesnt work. Uninstall / reinstall Clover.
> 
> If you need further help please feel free to re-open case.

I gave up on this, also you helped me on reddit, but we couldn't find a solution.

**Comment by ryanrudolfoba** [comment]
Only thing i can remember is this WinDeckOS?

If it is, its unsupported configuration
