### ISSUE TITLE
Does not find BlissOS

### ISSUE THREAD

**Issue by snowboyz0825** [ryanrudolfoba/SteamDeck-Clover-dualboot#80]
I have 3 OSes on my steam deck - SteamOS, Windows, and BlissOS. It finds windows and steam fine. Is there a config I can easily change or something so it does?

**Comment by ryanrudolfoba** [comment]
you'll have to add the BlissOS entry in the config.

backup config.plist, then edit it and add the entry for BlissOS.

this is sample entry for Bazzite on the config.plist -
![image](https://github.com/user-attachments/assets/b420f68a-774c-47a3-9b62-eff0b0a67da1)

adjust it for BlissOS. once that is done, run the install script again.
