### ISSUE TITLE
Bazzite: "Not enough space on the ESP partition"

### ISSUE THREAD

**Issue by Supernovva-97** [ryanrudolfoba/SteamDeck-Clover-dualboot#81]
Hey, I find your product/content very interesting and wanted to try it after not having the best experience with refind (not on current install) but I'm having some issues.

I have a Steam Deck OLED running Windows 11 and Bazzite on dual boot. Installed following bazzite dual-boot setup guide (https://docs.bazzite.gg/General/Installation_Guide/dual_boot_setup_guide/) specifically with this partition table after installing Win11 and shrinking the main partition: 

![{64617846-F7EC-421C-A267-D5E88EDF16D8}](https://github.com/user-attachments/assets/6da57430-1f50-4c4d-aa14-11e3f1cdb822)

After installation, I boot onto a live environment and disable windows' boot entry from the boot priority (sudo efibootmgr -b XXXX -A). Ending up with the following partition table:

![image](https://github.com/user-attachments/assets/c688a845-440e-47ce-a289-4f3cd5760c7e)

I then boot into windows and start following your guide. All goes well until it mounts and checks for space on the ESP partition:

![image](https://github.com/user-attachments/assets/476a32e0-910c-4bae-adfe-e7f787292907)

I read your script to see if I can figure something out and suspect it may have something to do with the fact that its mounting and checking nvme0n1p1 when /boot is at nvme0n1p5 and /boot/efi is at nvme0n1p4. Let me know if there's a reasonable fix or any advice you may have. Thanks!

**Comment by ryanrudolfoba** [comment]
sorry for late reply. i checked your screenshot and yes ESP is at nvme0n1p4

the script assumes that ESP is at nvme0n1p1 - i'll have to figure out a better way to determine this for Bazzite. for SteamOS its always at nvme0n1p1

for the meantime edit line 48 and change nvme0n1p1 to nvme0n1p4
![image](https://github.com/user-attachments/assets/2b915922-e1db-4da9-9d9c-f57ec18c3440)

**Comment by ChroniXmile** [comment]
I'm having a similar problem, changed the script to the correct efi for me (nvme0n1p5) and it installed, but status has a yellow caution sign. Always boots right to windows. ESP status doesn't return anything its just blank. Let me know what details you need and I'll update.
Thanks

**Comment by Supernovva-97** [comment]
Sorry for the late response too, haven't been using the deck much since.
I followed your advice and edited the script can confirm the results from ChroniXmile

> status has a yellow caution sign. Always boots right to windows. ESP status doesn't return anything its just blank.

Here's the installation output: 

![image](https://github.com/user-attachments/assets/65ee3200-637c-4da8-b72b-dedf57ef065f)

here's status from the toolbox, clover is listed in it, but I've been to boot into it so far:

![image](https://github.com/user-attachments/assets/e92aa2c7-0209-42eb-8532-6f31658a60e2)

I also tried disabling the new windows boot manager entry like i did last time (Mint live environment) but I'm unable to:

![image](https://github.com/user-attachments/assets/b5ee5de8-6aa3-4c0e-811e-ce9e84876475)

If you've had any success on a Bazzite/Windows dual boot system maybe you can share your setup instructions. In the mean time I'll try putting all bazzite partitions at the beginning of the drive and windows at the end of it and report the results. Cheers.

**Comment by Supernovva-97** [comment]
#

> I'll try putting all bazzite partitions at the beginning of the drive and windows at the end of it and report the results.

Same, windows is still first boot option.

I did manage to finally boot into clover though, by running the  [CloverWindows.bat](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/blob/main/CloverWindows/CloverWindows.bat) available in the repo, but there only was a bazzite option, no windows. Even then 1 out of every 2 times you'll be booting straight into windows, which isn't ideal.

**Comment by ryanrudolfoba** [comment]
The script is tested with the following config -

Bazzite/ SteamOS is installed before Windows.

Is that how yours are setup or different?

**Comment by lukee12zakk** [comment]
Hello. I have the same issue. I have installed windows 11 24h2 before bazzite. Followed a tutorial from https://youtu.be/yBHzVSDVEqw?si=ptmiLwBG_vMChuUR. After install, I go to bazzite and try to install the script. It gives me an error that is in the pic that I have left here. I don't know where the /esp directory/folder is so I also left a layout of the partitions. Thanks.


![20241112_141027.jpg](https://github.com/user-attachments/assets/67f931fb-323a-4dca-8667-f994675d1acf)

![20241112_141104.jpg](https://github.com/user-attachments/assets/ca1c4484-30dc-4c10-9863-fd71b4bd5b3d)

**Comment by ryanrudolfoba** [comment]
The script is tested with the following config -

Bazzite/ SteamOS is installed before Windows.
