### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by treeefxg** [ryanrudolfoba/SteamDeck-Clover-dualboot#82]
didnt added windows

Script is running on supported OS - SteamOS!
Clover Boot Manager - Thu Oct 3 02:00:39 PM CEST 2024
BIOS Version : F7A0131
OS Name : "SteamOS"
OS Version : 3.5.19
OS Build : 20240422.1
Kernel Version : Linux steamdeck 6.1.52-valve16-1-neptune-61 #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000 
x86_64 GNU/Linux
EFI dump files does not exist - no action needed.
Clover EFI entry exists! No need to re-add Clover.
SteamOS EFI entry exists! No need to re-add SteamOS.
Windows EFI backup does not exist.
Windows EFI needs to be disabled - done.
*** Current state of EFI entries ****
BootNext: 0000
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0001,0002
Boot0000* EFI Hard Drive (24102W800007-WD_BLACK SN770M 1TB)	
PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0)/NVMe(0x1,00-1B-44-8B-47-E7-71-CC)/HD(1,GPT,2bf1501e-3138-ed49-a0aa-b93207928694,0
x800,0x20000)RC
Boot0001* Clover - GUI Boot Manager	
HD(1,GPT,2bf1501e-3138-ed49-a0aa-b93207928694,0x800,0x20000)/File(EFIclovercloverx64.efi)
Boot0002* SteamOS	HD(1,GPT,2bf1501e-3138-ed49-a0aa-b93207928694,0x800,0x20000)/File(EFIsteamossteamcl.efi)
Boot0003* Windows Boot Manager	
HD(9,GPT,1ddca223-eae5-43f5-a48c-c4ceb3c1085e,0x5956f000,0xb0000)/File(EFIMicrosoftBootootmgfw.efi)RC
Boot0007* Windows Boot Manager	
HD(9,GPT,1ddca223-eae5-43f5-a48c-c4ceb3c1085e,0x5ddb3000,0x82000)/File(EFIMicrosoftBootootmgfw.efi)57494e444f575300
0100000088000000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d003500630064006400
2d0034006500370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d00000065000100000010000000
040000007fff0400
*** Current state of EFI partition ****
ESP partition: /dev/nvme0n1p1
ESP mount point: /esp
ESP allocated space: 64M
ESP used space: 15M
ESP free space: 50M

**Comment by ryanrudolfoba** [comment]
Where is Windows installed - on internal SSD or somewhere else?

What version of Windows are you using?

Please try this in konsole and paste output here -

`lsblk`

**Comment by treeefxg** [comment]
i already fixed it the boot files were in the wrong place
but thanks
