### ISSUE TITLE
Monitor doesn't work correctly in Windows until 3rd reboot

### ISSUE THREAD

**Issue by ZedKGaming** [ryanrudolfoba/SteamDeck-Clover-dualboot#83]
Steps to recreate:
1. Install Windows on an external SSD and make sure the monitor is the primary display in the Windows installation.
2. Boot into SteamOS and install Clover without any USB hubs or anything connected, just your Steam Deck.
3. Shutdown your Deck.
4. Plug in your USB hub with the external SSD and HDMI cable plugged into a monitor connected.
5. Boot up Clover, 1st issue arises, which is that Clover doesn't recognize the monitor for whatever reason, even when booting into Windows, it refuses to use the monitor screen, not even replugging it does anything.
6. Shutdown your Deck and reboot again, this time the monitor is used to show the Clover boot menu, and when booting into Windows, it works with the loading icon appearing. However, the 2nd issue arises when getting to the point where Windows logs me in, because while Windows thinks it's outputting video to the monitor, it isn't and is only outputting video to my Deck's screen. I didn't really test if replugging the HDMI cable fixes this specific issue here, but let's just go on.
7. Shutdown your Deck one more time, and finally, after 3 reboots, the monitor works correctly and Clover also works fine, no issues. 

This never happened to me in the previous version of your script (the one before you changed the icon of the Windows icon in Clover) so I really don't know what could be happening here.

**Comment by ryanrudolfoba** [comment]
Aug14 script uses Clover 5159.
Sep10 script still uses Clover 5159 although added logic on the script installation to detect if Bazzite or SteamOS.

as far as the main Clover progarm is concerned this are the same as both are on Clover 5159.

**Comment by ZedKGaming** [comment]
> Aug14 script uses Clover 5159. Sep10 script still uses Clover 5159 although added logic on the script installation to detect if Bazzite or SteamOS.
> 
> as far as the main Clover progarm is concerned this are the same as both are on Clover 5159.

Oh yeah, sorry about that, found out that this was a personal issue. But I have another problem which has been an issue since I've been using Clover since the beginning of August, which is sometimes the Windows bootloader takes over Clover and boots up REALLY slowly, like it takes forever for it to boot up.

And a quick question while you're here, how can I access the ... / Quick Access menu when booting into SteamOS? (the menu where I can select to boot into the previous version of SteamOS after an update)

**Comment by ryanrudolfoba** [comment]
> sometimes the Windows bootloader takes over Clover and boots up REALLY slowly, like it takes forever for it to boot up.
Usually that happens when there is a Windows update. Once Windows applies its own updates it takes over the boot loader, and takes a while to boot up as it still needs to finish installing the updates. Once its done, manually reboot to SteamOS and it will automatically fix the boot loader and Clover will be the top priority again.

> how can I access the ... / Quick Access menu when booting into SteamOS? (the menu where I can select to boot into the previous version of SteamOS after an update)

Power off the Steam Deck, while OFF press 3dots + power. Clover screen will show up, select SteamOS and it will display the recovery screen.
