### ISSUE TITLE
How to fixboot clover Steamos 3.6.20?
I tried the tutorial for 3.6.19 but not working. 

### ISSUE THREAD

**Issue by Marcusholoway428** [ryanrudolfoba/SteamDeck-Clover-dualboot#84]

**Comment by ryanrudolfoba** [comment]
what error are you getting?

**Comment by Marcusholoway428** [comment]
Does not go or flash in boot menu. It goes straight to OS that I set in BIOS. Steam or Windows. But before that I tried to fix by finding steamos.efi if I remember correctly the file name. Until now I am manually changing the boot using the vol down and power on.

**Comment by ryanrudolfoba** [comment]
This is because of SteamOS whitelist.

Uninstall Clover using Clover Toolbox. Clone the repo again to get the latest version that supports whitelist then install it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Marcusholoway428** [comment]
I think I deleted the clover toolbox. Is there other way to uninstall clover?

**Comment by ryanrudolfoba** [comment]
open konsole -

`cd ~/1Clover-tools`
`./Clover-Toolbox.sh`

![image](https://github.com/user-attachments/assets/4fbba555-e2e0-4543-afcb-556e52ce25c7)

**Comment by ryanrudolfoba** [comment]
feel free to update this if need further help.
