### ISSUE TITLE
Cannot boot to Windows while connected to external display

### ISSUE THREAD

**Issue by PlavorSeol** [ryanrudolfoba/SteamDeck-Clover-dualboot#85]
When booting up Steam Deck while it is connected to an external display via official Docking Station from Valve, after Windows shows the rotated loading screen, it crashes while showing nothing, and Steam Deck restarts itself and this repeats until Windows enters the automatic repair mode.
There is no issue when Steam Deck is not docked, or Clover is disabled or uninstalled.

## Step to reproduce
1. Connect an external display and power supply to Steam Deck Docking Station.
1. Connect Steam Deck to the dock.
1. Volume down + Power
1. Boot to SteamOS.
1. Install Clover.
1. Change the default OS to Windows.
1. Restart Steam Deck.

## Reproducible environments
* Steam Deck OLED
* Official Steam Deck Docking Station from Valve
* External display: AOC Q32V3S (Q32V3WG5, 2560 X 1440)
* Windows 11 23H2
* I think Clover status includes the rest.

<details>
  <summary>
    <h2>Clover status</h2>
  </summary>

```
Script is running on supported OS - SteamOS!
Clover Boot Manager - Tue Nov 5 08:56:09 AM KST 2024
BIOS Version : F7G0112
OS Name : "SteamOS"
OS Version : 3.6.20
OS Build : 20241030.1
Kernel Version : Linux PlavorSeol-SteamDeck-SteamOS 6.5.0-valve22-1-neptune-65-g9a338ed8a75e #1 SMP PREEMPT_DYNAMIC
Mon, 21 Oct 2024 19:06:57 +0000 x86_64 GNU/Linux
EFI dump files does not exist - no action needed.
Clover EFI entry exists! No need to re-add Clover.
SteamOS EFI entry exists! No need to re-add SteamOS.
Windows EFI backup exists. Check if Windows EFI needs to be disabled.
Windows EFI is already disabled - no action needed.
*** Current state of EFI entries ****
BootCurrent: 0001
Timeout: 0 seconds
BootOrder: 0001,0006
Boot0000* EFI Hard Drive (50026B7283435C9D-KINGSTON OM3PGP4512Q-A0)
PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0)/NVMe(0x1,00-26-B7-28-34-35-C9-D5)/HD(1,GPT,d942add6-3445-49a7-8cd6-333572d59545,0
x800,0x20000)RC
Boot0001* Clover - GUI Boot Manager
HD(1,GPT,d942add6-3445-49a7-8cd6-333572d59545,0x800,0x20000)/EFIclovercloverx64.efi
Boot0006* SteamOS	HD(1,GPT,d942add6-3445-49a7-8cd6-333572d59545,0x800,0x20000)/EFIsteamossteamcl.efi
Boot0007* Windows Boot Manager
HD(1,GPT,d942add6-3445-49a7-8cd6-333572d59545,0x800,0x20000)/EFIMicrosoftBootootmgfw.efi57494e444f57530001000000880
00000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d003400650
0370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d00000030000100000010000000040000007ff
f0400
*** Current state of EFI partition ****
ESP partition: /dev/nvme0n1p1
ESP mount point: /esp
ESP allocated space: 64M
ESP used space: 43M
ESP free space: 22M
```
</details>

**Comment by PlavorSeol** [comment]
Hello.
I tried all of old Clover versions that you mentioned, and none of them helped resolving this issue.
For 5159~5152, the result was same: Windows shows the rotated loading screen, then crashes. I've also seen Windows' automatic repair mode few times during the test.
For 5151, the script simply ends with "Error downloading Clover!".

**Comment by ryanrudolfoba** [comment]
Dors the error happen if you use a 1080p monitor? Could be a compatibility issue somewhere on the hardware that you are using.

**Comment by PlavorSeol** [comment]
I do not have any 1080p display.
However, I also tested with a 4K TV and the same thing happened.
This, and that 1440p monitor are only displays I have.

**Comment by ryanrudolfoba** [comment]
It could be related to this -

https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot?tab=readme-ov-file#known-issue

**Comment by ryanrudolfoba** [comment]
This points out to the hardware you are using.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PlavorSeol** [comment]
> This points out to the hardware you are using.

Sorry, I do not understand. Could you please elaborate what you mean?

**Comment by ryanrudolfoba** [comment]
Its a hardware compatibility issue. Clover boots up rotated on displays higher than 1080p (because the Steam Deck screen is native portrait) and in turn affects Windows. I dont have that issue as i use a 1080p display. It could also be the dock you are using.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PlavorSeol** [comment]
Regarding the dock, I am using the **official** dock, as I wrote in the description of this issue.
Is there anything I can do about this issue with what I have now?
I am okay with Clover showing the rotated screen, but absolutely not with making Windows unbootable at all when connected to my external display. I had to uninstall Clover for this.

**Comment by ryanrudolfoba** [comment]
im not able to fix this. workaround is use a display that does not exceed 1080p.
