### ISSUE TITLE
Windows sometimes won’t boot

### ISSUE THREAD

**Issue by RhanCandia** [ryanrudolfoba/SteamDeck-Clover-dualboot#86]
50% of the time, when booting Windows from Clover, it just shows the initial Steam Deck logo with the Windows loader below it then black screen.

Stays like that. I can tell it is still on because the fans are on. I tried waiting on it several times but even after 3 minutes it’s still just black screen. Tried pressing the power button once, nothing. Still black screen.

Then I would have to force shutdown the Deck by holding the power button until fans stop.

From there, booting the device, selecting Windows, it would turn on and fast. Gets to the lockscreen under 5 seconds.

Is there a log somewhere that I can extract when I encounter it again? Maybe it can help us figure out why it happens. 

SteamOS 3.6.20. Windows 24H2. Both in the Internal SSD.

**Comment by ryanrudolfoba** [comment]
This is a common issue with dual boot even without Clover.

Make sure fast startup and hibernate is disabled on the Windows side.

**Comment by RhanCandia** [comment]
I went ahead ahead and disabled hybernate and fast startup on Windows. I’ll observe and report back.
