### ISSUE TITLE
stuck in bootloop with WinDeckOS dualboot

### ISSUE THREAD

**Issue by minhnh94** [ryanrudolfoba/SteamDeck-Clover-dualboot#87]
Hi Ryan, thank you for the awesome tool! :)
I've followed your instruction about how to dual boot steamOS and WinDeckOS here https://www.reddit.com/r/WindowsOnDeck/comments/1dthtwx/clover_problems/ and was able to get it working.
The thing is, whenever I connect the steam deck to my 4k monitor (dell u2723qe fwiw) and start booting the steam deck up and choose WinDeckOS, it's always stuck at WindeckOS loading screen for a few seconds before being looped back into Clover OS selection screen once again. If I unplug the deck from the monitor then it would boot into WindeckOS if selected, but after that the steam deck would always skip Clover OS selection and boot straight into WindeckOS (until I choose to boot steamOS from the BIOS boot selection).
Do you have any idea on this?
Hope I can be shed some light on the issue. Thank you and best regards!

**Comment by ryanrudolfoba** [comment]
I'm glad you find it useful.

The reddit post linked I tried to provide best effort, but unfortunately WindeckOS is unsupported configuration.

Latest version of the script it has sanity checks so it won't install on WindeckOS.
