### ISSUE TITLE
Clover display errors on 4K TV

### ISSUE THREAD

**Issue by cinntoastcrunch** [ryanrudolfoba/SteamDeck-Clover-dualboot#9]
Whenever I power on the Steam Deck while connected to a 4K TV, Clover is displayed in the wrong orientation (sideways). I have tried two different USB-C hubs, and have tried it on another 4k display and the same issue appears. I don't think the issue is present on 1080p displays, as when I tried it there, Clover still boots in the normal orientation.

![IMG_0101 3](https://user-images.githubusercontent.com/128992153/227789912-e3c7b523-1a13-4295-ad68-9ace32eddecd.jpg)

**Comment by ryanrudolfoba** [comment]
sorry i cant fix this. i tried several iterations of the config but no success. this seems to be an issue with the Steam Deck itself using a portrait screen. i wish they used a landscape screen so no rotating is necessary.
